name: CI

on: push

jobs:
  install:
    name: Install
    strategy:
      fail-fast: false
      matrix:
          os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install gobang
        if: runner.os != 'windows'
        run: |
          brew update
          brew install tako8ki/tap/gobang
          gobang -h
      - name: Install gobang with scooop
        if: runner.os == 'windows'
        run: scoop install gobang

